bound method detection under python 3 requires actual class instance. at this point, pytest can successfully start.
fixes this:
INTERNALERROR>   File "/home/josh/dev/scratch/sentry3/src/sentry/runner/initializer.py", line 352, in setup_services
INTERNALERROR>     service.validate()
INTERNALERROR> TypeError: validate() missing 1 required positional argument: 'self'

most difficult fix to spot so far, by far.